version: '3.8'
services:
  crossbot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_CLIENT_ID
      - ACTIVE_PUZZLES_CHANNEL_CATEGORY_ID
      - OLD_PUZZLES_CHANNEL_CATEGORY_ID
      - PUZZ_WATCHERS_ROLE_ID
    ports:
      - 8080:8080