export const ACTIVE_PUZZLES_CHANNEL_CATEGORY_ID = process.env.ACTIVE_PUZZLES_CHANNEL_CATEGORY_ID || '';
export const OLD_PUZZLES_CHANNEL_CATEGORY_ID = process.env.OLD_PUZZLES_CHANNEL_CATEGORY_ID || '';
export const PUZZ_WATCHERS_ROLE_ID = process.env.PUZZ_WATCHERS_ROLE_ID || '';
