const ACTIVE_PUZZLES_CHANNEL_CATEGORY_ID = process.env.ACTIVE_PUZZLES_CHANNEL_CATEGORY_ID;
const OLD_PUZZLES_CHANNEL_CATEGORY_ID = process.env.OLD_PUZZLES_CHANNEL_CATEGORY_ID;
const PUZZ_WATCHERS_ROLE_ID = process.env.PUZZ_WATCHERS_ROLE_ID;

module.exports = {
	ACTIVE_PUZZLES_CHANNEL_CATEGORY_ID,
	OLD_PUZZLES_CHANNEL_CATEGORY_ID,
	PUZZ_WATCHERS_ROLE_ID,
}